from evidence_emitter import DevSigner, Ed25519Signer, Ed25519Verifier, emit, verify

from fixtures import fake_a2a_decision, full_context


def test_dev_signer_is_marked_non_production():
    s = DevSigner()
    assert s.production is False
    d = s.descriptor()
    assert d["production"] is False
    assert "not-for-production" not in d["key_id"]  # the key id is a plain label
    assert "not authentic" in d["note"]


def test_dev_signer_rejects_a_wrong_signature():
    s = DevSigner()
    msg = b"payload"
    good = s.sign(msg)
    assert s.verify(msg, good)
    assert not s.verify(msg, good[:-1] + bytes([good[-1] ^ 0xFF]))


def test_verify_surfaces_the_non_production_signer():
    report = verify(emit(fake_a2a_decision(), context=full_context()))
    assert report.signer_production is False
    assert "non-production" in report.summary()


def test_production_ed25519_round_trip():
    # The key is generated by the caller (the host), never by the library.
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    from cryptography.hazmat.primitives import serialization

    key = Ed25519PrivateKey.generate()
    priv_pem = key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    )
    pub_pem = key.public_key().public_bytes(
        serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo
    )

    signer = Ed25519Signer.from_private_pem(priv_pem, key_id="host-key-1")
    verifier = Ed25519Verifier.from_public_pem(pub_pem, key_id="host-key-1")

    pkg = emit(fake_a2a_decision(), context=full_context(), signer=signer)
    report = verify(pkg, signer=verifier)
    assert report.ok, report.findings
    assert report.signer_production is True


def test_a_dev_verifier_rejects_a_production_package():
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    from cryptography.hazmat.primitives import serialization

    key = Ed25519PrivateKey.generate()
    priv_pem = key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    )
    signer = Ed25519Signer.from_private_pem(priv_pem, key_id="host-key-2")
    pkg = emit(fake_a2a_decision(), context=full_context(), signer=signer)

    report = verify(pkg, signer=DevSigner())  # wrong verifier
    assert not report.ok
    assert "bad-signature" in {f["code"] for f in report.findings}
